sonar.projectKey=AbirDas1048_upokul
sonar.organization=abirdas1048

# Scan EVERYTHING (Laravel + frontend + public assets)
sonar.sources=app,resources,routes,public

# Tests folder
sonar.tests=tests

# Exclude noise / dependencies / build artifacts
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/build/**,public/hot,public/vendor/**

# Encoding
sonar.sourceEncoding=UTF-8
